/**
 * A/R Tax Services, LLC - Synthetic Demonstration Mock Data Layer
 * Strict synthetic data with masked identifiers and realistic accounting lifecycles.
 */

import { 
  DemoClient, 
  DemoEngagement, 
  DemoDocument, 
  DemoTransaction, 
  DemoReconciliationItem, 
  DemoPayrollRecord, 
  DemoTaxWorkpaper, 
  DemoAdvisoryCase, 
  DemoInvoice, 
  DemoAuditEvent,
  IntegrationRegistryItem
} from './types';

export const INITIAL_DEMO_CLIENTS: DemoClient[] = [
  {
    id: 'cli_perotti',
    name: 'Michael Perotti',
    businessName: 'Perotti Capital Holdings, LLC',
    entityType: 'S Corporation',
    einOrSsnMasked: 'XX-XXX4819',
    email: 'm.perotti@example.com',
    phone: '(678) 205-9486',
    address: '1420 Main St, Suite 400, Columbia, SC 29201',
    primaryJurisdiction: 'South Carolina (SC)',
    secondaryJurisdictions: ['North Carolina (NC)', 'Georgia (GA)'],
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Ready for Client Review',
    riskScore: 'Low',
    hasActiveNotice: false,
    hasOpenAmendment: false
  },
  {
    id: 'cli_summit',
    name: 'Sarah Jenkins',
    businessName: 'Summit Ridge Logistics Corp',
    entityType: 'C Corporation',
    einOrSsnMasked: 'XX-XXX9211',
    email: 's.jenkins@summitridge-demo.com',
    phone: '(803) 555-0144',
    address: '880 Industrial Blvd, Greenville, SC 29601',
    primaryJurisdiction: 'South Carolina (SC)',
    secondaryJurisdictions: ['Georgia (GA)', 'Florida (FL)', 'Tennessee (TN)'],
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Senior Review',
    riskScore: 'Medium',
    hasActiveNotice: true,
    hasOpenAmendment: false
  },
  {
    id: 'cli_harbor',
    name: 'David & Karen Vance',
    businessName: 'Harbor Dental Group LLP',
    entityType: 'Partnership',
    einOrSsnMasked: 'XX-XXX3190',
    email: 'dvance@harbordental-demo.org',
    phone: '(843) 555-8821',
    address: '210 Meeting St, Charleston, SC 29401',
    primaryJurisdiction: 'South Carolina (SC)',
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Corrections Required',
    riskScore: 'High',
    hasActiveNotice: false,
    hasOpenAmendment: false
  },
  {
    id: 'cli_apex',
    name: 'Jonathan Hayes',
    businessName: 'Apex Artisan Carpentry',
    entityType: 'Sole Proprietorship',
    einOrSsnMasked: 'XXX-XX-7812',
    email: 'j.hayes@apexwood-demo.com',
    phone: '(803) 555-6677',
    address: '412 Mill Pond Rd, Lexington, SC 29072',
    primaryJurisdiction: 'South Carolina (SC)',
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Awaiting Documents',
    riskScore: 'Medium',
    hasActiveNotice: false,
    hasOpenAmendment: false
  },
  {
    id: 'cli_beacon',
    name: 'Dr. Evelyn Reed',
    businessName: 'Beacon Hope Community Foundation',
    entityType: 'Nonprofit',
    einOrSsnMasked: 'XX-XXX5541',
    email: 'ereed@beaconhope-demo.org',
    phone: '(803) 555-9012',
    address: '120 Assembly St, Columbia, SC 29201',
    primaryJurisdiction: 'Federal (IRS Form 990)',
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Tax Preparation',
    riskScore: 'Low',
    hasActiveNotice: false,
    hasOpenAmendment: false
  },
  {
    id: 'cli_clark',
    name: 'Robert & Cynthia Clark',
    businessName: 'Palmetto Palms Rental Properties (4 Units)',
    entityType: 'Individual',
    einOrSsnMasked: 'XXX-XX-4421',
    email: 'rclark@clarkestate-demo.com',
    phone: '(843) 555-3211',
    address: '74 Oceanside Way, Hilton Head, SC 29928',
    primaryJurisdiction: 'South Carolina (SC)',
    secondaryJurisdictions: ['North Carolina (NC)'],
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Notice or Audit Open',
    riskScore: 'High',
    hasActiveNotice: true,
    hasOpenAmendment: false
  },
  {
    id: 'cli_novak',
    name: 'Dr. Gregory Novak',
    businessName: 'Novak Biomedical Consulting',
    entityType: 'S Corporation',
    einOrSsnMasked: 'XX-XXX1187',
    email: 'g.novak@novakbiomed-demo.com',
    phone: '(803) 555-4499',
    address: '330 Innovation Way, Rock Hill, SC 29730',
    primaryJurisdiction: 'South Carolina (SC)',
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Amendment Open',
    riskScore: 'Medium',
    hasActiveNotice: false,
    hasOpenAmendment: true
  },
  {
    id: 'cli_closed_vintage',
    name: 'Marcus & Linda Sterling',
    businessName: 'Vintage Mercantile LLC (Dissolved)',
    entityType: 'Partnership',
    einOrSsnMasked: 'XX-XXX6630',
    email: 'm.sterling@vintagemerc-demo.com',
    phone: '(803) 555-8120',
    address: '500 Gervais St, Columbia, SC 29201',
    primaryJurisdiction: 'South Carolina (SC)',
    assignedAccountantId: 'usr_acc_marcus',
    assignedAccountantName: 'Marcus Vance, EA',
    assignedReviewerId: 'usr_rev_elena',
    assignedReviewerName: 'Elena Rostova, CPA',
    status: 'Archived',
    riskScore: 'Low',
    hasActiveNotice: false,
    hasOpenAmendment: false
  }
];

export const INITIAL_DEMO_ENGAGEMENTS: DemoEngagement[] = [
  {
    id: 'eng_2025_perotti',
    clientId: 'cli_perotti',
    clientName: 'Michael Perotti',
    businessName: 'Perotti Capital Holdings, LLC',
    entityType: 'S Corporation',
    taxYear: 2025,
    jurisdiction: 'Federal & SC',
    formType: 'Form 1120-S & SC1120S',
    currentStage: 'Sign',
    currentStatus: 'Ready for Client Review',
    assignedStaff: 'Marcus Vance, EA (Prep) / Elena Rostova, CPA (QC)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 85,
    statutoryDeadline: 'March 15, 2026',
    internalDeadline: 'March 1, 2026',
    riskLevel: 'Low',
    missingRequirements: [],
    lastActivity: 'Elena Rostova, CPA approved return package. Released for client signature.',
    nextAction: 'Client review of Form 1120-S and authorization via Form 8879-S demonstration.',
    clientResponsibility: 'Inspect Form 8879-S, verify Officer Compensation, and complete simulated signature.',
    staffResponsibility: 'Monitor signature completion and queue for final simulated e-file transmission.',
    approvalState: 'Reviewer Approved',
    feeAmount: 3250.00,
    feeStatus: 'Invoiced'
  },
  {
    id: 'eng_2025_summit',
    clientId: 'cli_summit',
    clientName: 'Sarah Jenkins',
    businessName: 'Summit Ridge Logistics Corp',
    entityType: 'C Corporation',
    taxYear: 2025,
    jurisdiction: 'Multi-State (SC, GA, FL, TN)',
    formType: 'Form 1120 & Multi-State Apportionment',
    currentStage: 'Review',
    currentStatus: 'Senior Review',
    assignedStaff: 'Marcus Vance, EA (Prep) / Elena Rostova, CPA (QC)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 70,
    statutoryDeadline: 'April 15, 2026',
    internalDeadline: 'March 25, 2026',
    riskLevel: 'Medium',
    missingRequirements: ['Georgia Apportionment Schedule (Form 600)', 'Depreciation Asset Additions'],
    lastActivity: 'Preparer submitted Section 179 depreciation adjustments for senior review.',
    nextAction: 'Elena Rostova verifying multi-state nexus thresholds and apportionment factors.',
    clientResponsibility: 'Provide bill of lading state breakdown if requested.',
    staffResponsibility: 'Complete Schedule M-1 and book-to-tax trial balance reconciliation.',
    approvalState: 'Pending Review',
    feeAmount: 5800.00,
    feeStatus: 'Invoiced'
  },
  {
    id: 'eng_2025_harbor',
    clientId: 'cli_harbor',
    clientName: 'David & Karen Vance',
    businessName: 'Harbor Dental Group LLP',
    entityType: 'Partnership',
    taxYear: 2025,
    jurisdiction: 'Federal & SC',
    formType: 'Form 1065 & Schedules K-1',
    currentStage: 'Prepare Taxes',
    currentStatus: 'Corrections Required',
    assignedStaff: 'Marcus Vance, EA (Prep) / Elena Rostova, CPA (QC)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 55,
    statutoryDeadline: 'March 15, 2026',
    internalDeadline: 'March 5, 2026',
    riskLevel: 'High',
    missingRequirements: ['Guaranteed Payments Allocation Sheet', 'Partner Capital Account Reconciliation'],
    lastActivity: 'Senior Reviewer flagged $42,500 variance between book draws and guaranteed payments.',
    nextAction: 'Preparer Marcus Vance resolving reviewer diagnostic notes and updating Schedule M-2.',
    clientResponsibility: 'Confirm 2025 partnership distribution agreement amendment.',
    staffResponsibility: 'Adjust partner basis worksheets and resubmit to Senior Review queue.',
    approvalState: 'Corrections Required',
    feeAmount: 4200.00,
    feeStatus: 'Invoiced'
  },
  {
    id: 'eng_2025_apex',
    clientId: 'cli_apex',
    clientName: 'Jonathan Hayes',
    businessName: 'Apex Artisan Carpentry',
    entityType: 'Sole Proprietorship',
    taxYear: 2025,
    jurisdiction: 'Federal & SC',
    formType: 'Form 1040 (Schedule C & SE)',
    currentStage: 'Collect',
    currentStatus: 'Awaiting Documents',
    assignedStaff: 'Samuel Rivera (Bookkeeper) / Marcus Vance (Tax)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 25,
    statutoryDeadline: 'April 15, 2026',
    internalDeadline: 'April 1, 2026',
    riskLevel: 'Medium',
    missingRequirements: ['1099-K Payment Processor Report', 'Vehicle Mileage Log', 'Home Office Square Footage'],
    lastActivity: 'Automated 7-day document request reminder issued to client.',
    nextAction: 'Client to upload 1099-K statement and complete mileage questionnaire.',
    clientResponsibility: 'Submit missing 1099-K and expense receipts through portal.',
    staffResponsibility: 'Follow up via secure client message.',
    approvalState: 'Pending Preparation',
    feeAmount: 1450.00,
    feeStatus: 'Unbilled'
  },
  {
    id: 'eng_2025_beacon',
    clientId: 'cli_beacon',
    clientName: 'Dr. Evelyn Reed',
    businessName: 'Beacon Hope Community Foundation',
    entityType: 'Nonprofit',
    taxYear: 2025,
    jurisdiction: 'Federal (IRS Form 990)',
    formType: 'Form 990 (Return of Organization Exempt From Income Tax)',
    currentStage: 'Prepare Taxes',
    currentStatus: 'Tax Preparation',
    assignedStaff: 'Marcus Vance, EA (Prep)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 60,
    statutoryDeadline: 'May 15, 2026',
    internalDeadline: 'May 1, 2026',
    riskLevel: 'Low',
    missingRequirements: ['Schedule A Public Support Percentage Verification'],
    lastActivity: 'Program service revenue and functional expenses mapped to Part IX.',
    nextAction: 'Finalize governance policies (Part VI) and officer compensation disclosure.',
    clientResponsibility: 'Board approval of draft Form 990 review copy.',
    staffResponsibility: 'Complete Schedule B contributor confidentiality checklist.',
    approvalState: 'Pending Preparation',
    feeAmount: 3800.00,
    feeStatus: 'Invoiced'
  },
  {
    id: 'eng_notice_clark',
    clientId: 'cli_clark',
    clientName: 'Robert & Cynthia Clark',
    businessName: 'Palmetto Palms Rental Properties',
    entityType: 'Individual',
    taxYear: 2023,
    jurisdiction: 'IRS Exam Division',
    formType: 'Notice CP2000 Response & Audit Workpapers',
    currentStage: 'Monitor',
    currentStatus: 'Notice or Audit Open',
    assignedStaff: 'Desmond Hinds (Lead) / Marcus Vance (Research)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 90,
    statutoryDeadline: 'March 28, 2026',
    internalDeadline: 'March 20, 2026',
    riskLevel: 'High',
    missingRequirements: [],
    lastActivity: 'Formal written protest and rebuttal exhibits prepared with Form 2848 Power of Attorney.',
    nextAction: 'Senior review of rebuttal packet before certified mail simulated delivery.',
    clientResponsibility: 'Review draft response statement and sign Form 2848 demonstration.',
    staffResponsibility: 'Transmit rebuttal response with substantiating 1099-S escrow records.',
    approvalState: 'Pending Review',
    feeAmount: 2200.00,
    feeStatus: 'Paid (Simulated)'
  },
  {
    id: 'eng_amend_novak',
    clientId: 'cli_novak',
    clientName: 'Dr. Gregory Novak',
    businessName: 'Novak Biomedical Consulting',
    entityType: 'S Corporation',
    taxYear: 2024,
    jurisdiction: 'Federal & SC',
    formType: 'Form 1120-X & Amended SC1120S',
    currentStage: 'Plan',
    currentStatus: 'Amendment Open',
    assignedStaff: 'Desmond Hinds (Advisory) / Marcus Vance (Prep)',
    assignedPreparerId: 'usr_acc_marcus',
    assignedReviewerId: 'usr_rev_elena',
    completionPercentage: 40,
    statutoryDeadline: 'October 15, 2027',
    internalDeadline: 'April 15, 2026',
    riskLevel: 'Medium',
    missingRequirements: ['Retroactive R&D Payroll Tax Credit Certification (Form 8974)'],
    lastActivity: 'Advisory analysis established $18,400 unclaimed research expenditure credit.',
    nextAction: 'Draft amended tax line allocations and recalculate shareholder K-1s.',
    clientResponsibility: 'Provide time-tracking logs for qualifying biomedical research staff.',
    staffResponsibility: 'Finalize Form 6765 credit calculation.',
    approvalState: 'Pending Preparation',
    feeAmount: 2600.00,
    feeStatus: 'Invoiced'
  }
];

export const INITIAL_DEMO_DOCUMENTS: DemoDocument[] = [
  {
    id: 'doc_perotti_w2_1',
    clientId: 'cli_perotti',
    engagementId: 'eng_2025_perotti',
    fileName: 'Perotti_Officer_W2_2025.pdf',
    fileSize: '1.24 MB',
    fileType: 'application/pdf',
    category: 'Form W-2 (Wage Statement)',
    taxYear: 2025,
    uploadedAt: '2026-02-10T14:30:00Z',
    uploadedBy: 'Michael Perotti',
    sha256Hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    malwareScanStatus: 'clean (simulated)',
    status: 'Verified',
    notes: 'Officer compensation verified against general ledger account 6010.'
  },
  {
    id: 'doc_perotti_bank_q4',
    clientId: 'cli_perotti',
    engagementId: 'eng_2025_perotti',
    fileName: 'First_Citizens_Operating_Q4_2025.pdf',
    fileSize: '3.45 MB',
    fileType: 'application/pdf',
    category: 'Bank & Credit Statements',
    taxYear: 2025,
    uploadedAt: '2026-01-28T09:15:00Z',
    uploadedBy: 'Michael Perotti',
    sha256Hash: '4a6b28f8287d3a2414e86a51d9d93e119421ec28f7ff27c6efba5e632b781190',
    malwareScanStatus: 'clean (simulated)',
    status: 'Verified',
    notes: 'Closing balance of $184,920.44 reconciled to trial balance.'
  },
  {
    id: 'doc_perotti_draft_return',
    clientId: 'cli_perotti',
    engagementId: 'eng_2025_perotti',
    fileName: 'Draft_Form_1120S_Client_Review_Package.pdf',
    fileSize: '4.80 MB',
    fileType: 'application/pdf',
    category: 'Tax Return Package',
    taxYear: 2025,
    uploadedAt: '2026-03-01T16:00:00Z',
    uploadedBy: 'Elena Rostova, CPA',
    sha256Hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    malwareScanStatus: 'clean (simulated)',
    status: 'Verified',
    notes: 'Senior Reviewer certified return ready for client review and signature.'
  },
  {
    id: 'doc_summit_1120_sched',
    clientId: 'cli_summit',
    engagementId: 'eng_2025_summit',
    fileName: 'Summit_Ridge_Fixed_Assets_2025.xlsx',
    fileSize: '2.10 MB',
    fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    category: 'Depreciation & Fixed Assets',
    taxYear: 2025,
    uploadedAt: '2026-02-14T11:20:00Z',
    uploadedBy: 'Sarah Jenkins',
    sha256Hash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    malwareScanStatus: 'clean (simulated)',
    status: 'Verified'
  },
  {
    id: 'doc_clark_notice',
    clientId: 'cli_clark',
    engagementId: 'eng_notice_clark',
    fileName: 'IRS_Notice_CP2000_TY2023.pdf',
    fileSize: '2.80 MB',
    fileType: 'application/pdf',
    category: 'IRS Notice / Examination',
    taxYear: 2023,
    uploadedAt: '2026-02-01T10:00:00Z',
    uploadedBy: 'Robert Clark',
    sha256Hash: '99887766554433221100aabbccddeeff99887766554433221100aabbccddeeff',
    malwareScanStatus: 'clean (simulated)',
    status: 'Verified',
    notes: 'IRS inquiry regarding unreported 1099-S real estate escrow proceeds.'
  }
];

export const INITIAL_DEMO_TRANSACTIONS: DemoTransaction[] = [
  {
    id: 'txn_01',
    clientId: 'cli_perotti',
    clientName: 'Perotti Capital Holdings LLC',
    date: '2025-12-18',
    description: 'Adobe Creative Cloud Enterprise',
    amount: 189.99,
    type: 'debit',
    category: 'Software & Cloud Subscriptions',
    confidence: 99,
    account: 'First Citizens Checking (...4810)',
    status: 'Categorized',
    receiptAttached: true
  },
  {
    id: 'txn_02',
    clientId: 'cli_perotti',
    clientName: 'Perotti Capital Holdings LLC',
    date: '2025-12-20',
    description: 'South Carolina Department of Revenue Withholding',
    amount: 1450.00,
    type: 'debit',
    category: 'State Payroll Taxes Payable',
    confidence: 98,
    account: 'First Citizens Checking (...4810)',
    status: 'Categorized',
    receiptAttached: true
  },
  {
    id: 'txn_03',
    clientId: 'cli_perotti',
    clientName: 'Perotti Capital Holdings LLC',
    date: '2025-12-22',
    description: 'Client Retainer Wire - Palmetto Ventures',
    amount: 12500.00,
    type: 'credit',
    category: 'Advisory & Consulting Revenue',
    confidence: 95,
    account: 'First Citizens Checking (...4810)',
    status: 'Categorized',
    receiptAttached: false
  },
  {
    id: 'txn_04',
    clientId: 'cli_perotti',
    clientName: 'Perotti Capital Holdings LLC',
    date: '2025-12-28',
    description: 'Delta Air Lines Travel - Atlanta Conference',
    amount: 482.40,
    type: 'debit',
    category: 'Travel & Lodging',
    confidence: 92,
    account: 'Amex Business Platinum (...9002)',
    status: 'Categorized',
    receiptAttached: true
  },
  {
    id: 'txn_05',
    clientId: 'cli_summit',
    clientName: 'Summit Ridge Logistics Corp',
    date: '2025-12-15',
    description: 'Unidentified Vendor Check #4092',
    amount: 8750.00,
    type: 'debit',
    category: 'Uncategorized Expense',
    confidence: 35,
    account: 'Wells Fargo Operating (...1922)',
    status: 'Needs Review',
    receiptAttached: false
  }
];

export const INITIAL_DEMO_RECONCILIATIONS: DemoReconciliationItem[] = [
  {
    id: 'rec_perotti_dec',
    clientId: 'cli_perotti',
    accountName: 'First Citizens Commercial Checking (...4810)',
    statementDate: '2025-12-31',
    statementBalance: 184920.44,
    bookBalance: 184920.44,
    difference: 0.00,
    status: 'Approved by CPA',
    preparedBy: 'Samuel Rivera (Bookkeeper)',
    preparedAt: '2026-01-12T14:00:00Z',
    approvedBy: 'Elena Rostova, CPA',
    approvedAt: '2026-01-15T09:30:00Z'
  },
  {
    id: 'rec_summit_dec',
    clientId: 'cli_summit',
    accountName: 'Wells Fargo Commercial Operating (...1922)',
    statementDate: '2025-12-31',
    statementBalance: 412850.18,
    bookBalance: 404100.18,
    difference: 8750.00,
    status: 'Exceptions Exist',
    preparedBy: 'Samuel Rivera (Bookkeeper)',
    preparedAt: '2026-01-18T16:20:00Z'
  },
  {
    id: 'rec_harbor_dec',
    clientId: 'cli_harbor',
    accountName: 'Pinnacle Bank Operating (...8831)',
    statementDate: '2025-12-31',
    statementBalance: 96420.00,
    bookBalance: 96420.00,
    difference: 0.00,
    status: 'Prepared (Awaiting Review)',
    preparedBy: 'Samuel Rivera (Bookkeeper)',
    preparedAt: '2026-02-05T11:00:00Z'
  }
];

export const INITIAL_DEMO_PAYROLL: DemoPayrollRecord[] = [
  {
    id: 'pr_2026_02_biweekly',
    clientId: 'cli_perotti',
    payPeriod: '2026-02-01 to 2026-02-14',
    payDate: '2026-02-20',
    employeeCount: 6,
    contractorCount: 2,
    grossPay: 28400.00,
    federalWithholding: 4120.00,
    ficaWithholding: 2172.60,
    stateWithholding: 1420.00,
    netPay: 20687.40,
    status: 'Calculated (Simulated)'
  },
  {
    id: 'pr_2026_01_biweekly',
    clientId: 'cli_summit',
    payPeriod: '2026-01-15 to 2026-01-31',
    payDate: '2026-02-05',
    employeeCount: 24,
    contractorCount: 8,
    grossPay: 94250.00,
    federalWithholding: 14600.00,
    ficaWithholding: 7210.12,
    stateWithholding: 4950.00,
    netPay: 67489.88,
    status: 'Approved'
  }
];

export const INITIAL_DEMO_WORKPAPERS: DemoTaxWorkpaper[] = [
  {
    id: 'wp_perotti_01',
    engagementId: 'eng_2025_perotti',
    clientId: 'cli_perotti',
    title: 'Officer Compensation Substantiation',
    section: 'Form 1120-S, Line 7',
    formLine: 'Line 7 - Compensation of Officers',
    bookAmount: 145000.00,
    taxAdjustment: 0.00,
    taxAmount: 145000.00,
    notes: 'RCReports industry benchmark supports $145,000 reasonable salary for managing executive.',
    preparedBy: 'Marcus Vance, EA',
    reviewedBy: 'Elena Rostova, CPA',
    status: 'Reviewer Approved'
  },
  {
    id: 'wp_perotti_02',
    engagementId: 'eng_2025_perotti',
    clientId: 'cli_perotti',
    title: 'Meals & Entertainment 50% Limitation',
    section: 'Schedule M-1, Line 5',
    formLine: 'Schedule M-1 - Expenses recorded on books not deducted on return',
    bookAmount: 8450.00,
    taxAdjustment: -4225.00,
    taxAmount: 4225.00,
    notes: '50% statutory disallowance applied under IRC Sec 274(n).',
    preparedBy: 'Marcus Vance, EA',
    reviewedBy: 'Elena Rostova, CPA',
    status: 'Reviewer Approved'
  },
  {
    id: 'wp_summit_01',
    engagementId: 'eng_2025_summit',
    clientId: 'cli_summit',
    title: 'Section 179 Accelerated Depreciation',
    section: 'Form 4562, Part I',
    formLine: 'Line 12 - Total Section 179 deduction',
    bookAmount: 48000.00,
    taxAdjustment: 124000.00,
    taxAmount: 172000.00,
    notes: 'New freight logistics forklifts and cold storage equipment placed in service in Q3.',
    preparedBy: 'Marcus Vance, EA',
    status: 'Ready for Review'
  }
];

export const INITIAL_DEMO_ADVISORY: DemoAdvisoryCase[] = [
  {
    id: 'adv_perotti_entity',
    clientId: 'cli_perotti',
    clientName: 'Michael Perotti',
    title: 'S-Corp Distribution vs. Salary Optimization',
    taxYear: 2026,
    jurisdiction: 'Federal & SC',
    assumptions: 'Projected net operating income $340,000; reasonable executive salary benchmarked at $150,000.',
    sourceInformation: '2024-2025 historical P&L, RCReports executive compensation survey for Columbia, SC MSA.',
    estimatedImpact: 'Estimated self-employment/FICA tax savings of $18,240 annually.',
    confidence: 96,
    requiredProfessionalReview: 'Annual review of officer time allocation and W-2 payroll quarterly deposits.',
    clientAction: 'Authorize payroll schedule adjustment starting Q1 2026.',
    dueDate: '2026-03-31',
    status: 'Presented'
  },
  {
    id: 'adv_summit_nexus',
    clientId: 'cli_summit',
    clientName: 'Sarah Jenkins',
    title: 'Multi-State Economic Nexus & Apportionment Review',
    taxYear: 2026,
    jurisdiction: 'North Carolina, Georgia, Florida',
    assumptions: 'Out-of-state delivery routes exceeding $100k threshold or 200 remote transactions in NC and GA.',
    sourceInformation: '2025 shipping destination manifest and state DOR administrative rules.',
    estimatedImpact: 'Mitigates potential $45,000 back-tax liability and penalties across 3 state tax departments.',
    confidence: 92,
    requiredProfessionalReview: 'State tax legal specialist coordination and voluntary disclosure agreement evaluation.',
    clientAction: 'Submit detailed shipping logs categorized by destination zip code.',
    dueDate: '2026-04-15',
    status: 'Draft'
  }
];

export const INITIAL_DEMO_INVOICES: DemoInvoice[] = [
  {
    id: 'inv_2026_01',
    clientId: 'cli_perotti',
    clientName: 'Michael Perotti (Perotti Capital Holdings LLC)',
    engagementId: 'eng_2025_perotti',
    invoiceNumber: 'INV-2026-0144',
    issueDate: '2026-02-15',
    dueDate: '2026-03-15',
    amount: 3250.00,
    balanceDue: 3250.00,
    status: 'Sent',
    items: [
      { description: 'Annual Corporate Tax Preparation (Form 1120-S & SC1120S)', total: 2450.00 },
      { description: 'Quarterly Bookkeeping Review & Year-End Adjusting Entries', total: 800.00 }
    ]
  },
  {
    id: 'inv_2026_02',
    clientId: 'cli_summit',
    clientName: 'Summit Ridge Logistics Corp',
    engagementId: 'eng_2025_summit',
    invoiceNumber: 'INV-2026-0145',
    issueDate: '2026-02-18',
    dueDate: '2026-03-18',
    amount: 5800.00,
    balanceDue: 5800.00,
    status: 'Sent',
    items: [
      { description: 'Multi-State C-Corporation Tax Return (Form 1120)', total: 3800.00 },
      { description: 'Multi-State Apportionment Schedules (GA, FL, TN, SC)', total: 2000.00 }
    ]
  },
  {
    id: 'inv_2026_03',
    clientId: 'cli_clark',
    clientName: 'Robert & Cynthia Clark',
    engagementId: 'eng_notice_clark',
    invoiceNumber: 'INV-2026-0112',
    issueDate: '2026-02-02',
    dueDate: '2026-02-16',
    amount: 2200.00,
    balanceDue: 0.00,
    status: 'Paid (Simulated)',
    items: [
      { description: 'IRS CP2000 Audit Representation & Formal Written Rebuttal', total: 2200.00 }
    ]
  }
];

export const INITIAL_DEMO_AUDIT_LOGS: DemoAuditEvent[] = [
  {
    id: 'aud_101',
    timestamp: '2026-03-02T10:14:22Z',
    user: 'Elena Rostova, CPA',
    role: 'reviewer',
    action: 'Approved Final Return Package',
    record: 'Engagement: eng_2025_perotti (Form 1120-S)',
    result: 'Success (Simulated)',
    reason: 'Verified all 14 review checklist items, book-to-tax reconciliation, and officer compensation.'
  },
  {
    id: 'aud_102',
    timestamp: '2026-03-02T09:40:11Z',
    user: 'Marcus Vance, EA',
    role: 'accountant',
    action: 'Submitted Return for Senior Review',
    record: 'Engagement: eng_2025_summit (Form 1120)',
    result: 'Success (Simulated)',
    reason: 'Completed Schedule M-1 and asset additions workpapers.'
  },
  {
    id: 'aud_103',
    timestamp: '2026-03-01T15:22:45Z',
    user: 'Elena Rostova, CPA',
    role: 'reviewer',
    action: 'Issued Correction Request',
    record: 'Engagement: eng_2025_harbor (Form 1065)',
    result: 'Warning (Simulated)',
    reason: 'Partner draw variance of $42,500 requires recalculation against Schedule K-1.'
  },
  {
    id: 'aud_104',
    timestamp: '2026-02-28T11:15:00Z',
    user: 'Samuel Rivera',
    role: 'bookkeeper',
    action: 'Completed Bank Reconciliation',
    record: 'Account: First Citizens Commercial Checking (...4810)',
    result: 'Success (Simulated)',
    reason: 'Zero reconciliation variance confirmed.'
  },
  {
    id: 'aud_105',
    timestamp: '2026-02-27T16:00:19Z',
    user: 'System Security Watchdog',
    role: 'compliance',
    action: 'Maker-Checker Gate Verification',
    record: 'Return: Form 1120-S eng_2025_perotti',
    result: 'Success (Simulated)',
    reason: 'Confirmed distinct identities: Preparer Marcus Vance ≠ Reviewer Elena Rostova.'
  }
];

export const FUTURE_INTEGRATION_REGISTRY: IntegrationRegistryItem[] = [
  {
    id: 'int_firebase_auth',
    name: 'Firebase Authentication & Multi-Factor Engine',
    category: 'Identity',
    businessPurpose: 'Federated enterprise single sign-on, hardware FIDO2 key verification, and secure passwordless client tokens.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_PROJECT_ID'],
    requiredAuthorization: 'OAuth 2.0 / OpenID Connect',
    dataExchanged: 'User identifiers, encrypted session JWTs, MFA challenge tokens',
    webhookRequirement: 'Auth state trigger cloud functions',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_firestore_db',
    name: 'Google Cloud Firestore Enterprise Vault',
    category: 'Cloud Database',
    businessPurpose: 'Immutable client records, durable engagement ledgers, and Section 7216 compliant retention storage.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['GCP_PROJECT_ID', 'GOOGLE_APPLICATION_CREDENTIALS_JSON'],
    requiredAuthorization: 'GCP Service Account with Cloud Datastore User IAM',
    dataExchanged: 'Structured tax metadata, workflow transitions, encrypted workpaper summaries',
    webhookRequirement: 'Firestore document mutation triggers',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_irs_efile',
    name: 'IRS Authorized E-File Transmitter & MeF Modernized E-File',
    category: 'IRS & Government E-File',
    businessPurpose: 'Direct statutory transmission of Forms 1040, 1065, 1120, 1120-S, 990 to IRS MeF gateway.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['IRS_EFIN', 'IRS_ETIN', 'MEF_TRANSMITTER_CERT_PEM', 'TRANSMISSION_PASSWORD'],
    requiredAuthorization: 'Authorized IRS E-File Provider Agreement & Annual Security Certification',
    dataExchanged: 'Signed XML tax filing payloads, binary PDF attachments, IRS acknowledgment receipts',
    webhookRequirement: 'IRS MeF Status Polling & Webhook Acknowledgments (941/1040/1120)',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_sc_dor_efile',
    name: 'South Carolina Department of Revenue (MyDORWAY API)',
    category: 'IRS & Government E-File',
    businessPurpose: 'State corporate, partnership, and withholding electronic submission to SC DOR.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['SC_DOR_TRANSMITTER_ID', 'SC_STATE_CERTIFICATE_PEM'],
    requiredAuthorization: 'SC DOR Third-Party Tax Preparer Electronic Filing Authorization',
    dataExchanged: 'SC1040, SC1120, SC1120S, and WH-1605 payroll reports',
    webhookRequirement: 'State acknowledgment push notifications',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_qbo_api',
    name: 'Intuit QuickBooks Online Accountant Sync',
    category: 'Accounting Feeds',
    businessPurpose: 'Bi-directional general ledger sync, bank feed reconciliation, and journal entry posting.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['QBO_CLIENT_ID', 'QBO_CLIENT_SECRET', 'QBO_REALM_ID'],
    requiredAuthorization: 'OAuth 2.0 with Accounting Scope',
    dataExchanged: 'Chart of accounts, trial balances, transaction register, vendors, customers',
    webhookRequirement: 'Intuit CDC (Change Data Capture) Webhooks',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_stripe_billing',
    name: 'Stripe Corporate Billing & ACH Direct Debit',
    category: 'Payment Gateway',
    businessPurpose: 'Client retainer processing, credit card fee collection, and Nacha-compliant ACH debit.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['STRIPE_SECRET_KEY', 'STRIPE_WEBHOOK_SIGNING_SECRET'],
    requiredAuthorization: 'PCI-DSS Level 1 Service Provider Agreement',
    dataExchanged: 'Invoice amounts, payment tokens, customer IDs (zero plaintext card storage)',
    webhookRequirement: 'payment_intent.succeeded, charge.failed, invoice.paid webhooks',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_docusign_8879',
    name: 'DocuSign / IRS 8879 E-Signature Appliance',
    category: 'E-Signature',
    businessPurpose: 'Tamper-evident, knowledge-based authentication (KBA) e-signature on Form 8879 and engagement letters.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['DOCUSIGN_INTEGRATOR_KEY', 'DOCUSIGN_USER_ID', 'DOCUSIGN_RSA_PRIVATE_KEY'],
    requiredAuthorization: 'ESIGN Act & IRS Pub 1345 Compliant KBA Signature Workflow',
    dataExchanged: 'Envelopes, audit certificates of completion, signer IP & timestamp hashes',
    webhookRequirement: 'DocuSign Connect event webhooks',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_clamav_scanner',
    name: 'ClamAV / Cloud Storage Anti-Malware Sandbox',
    category: 'Cloud Database',
    businessPurpose: 'Automated real-time heuristic anti-malware and trojan payload analysis of uploaded tax dossiers.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['CLAMAV_CONTAINER_HOST', 'CLAMAV_PORT'],
    requiredAuthorization: 'Internal Network Socket',
    dataExchanged: 'Binary stream scanning, signature database updates, quarantine notices',
    webhookRequirement: 'Scan completion callback',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  },
  {
    id: 'int_gemini_docai',
    name: 'Google Gemini 2.5 Flash / Document AI Engine',
    category: 'AI & OCR',
    businessPurpose: 'Automated OCR extraction, W-2/1099 box parsing, and reconciliation anomaly detection.',
    currentStatus: 'Not Configured',
    requiredCredentials: ['GEMINI_API_KEY', 'GCP_DOCAI_PROCESSOR_ID'],
    requiredAuthorization: 'Enterprise Cloud Run / GenAI Private Endpoints',
    dataExchanged: 'Sanitized text snippets, structured JSON field mappings, confidence metrics',
    webhookRequirement: 'Asynchronous document batch completion webhooks',
    securityReviewStatus: 'Pending Phase 2 Architecture Review',
    productionReadiness: 'Planned Future Integration'
  }
];
